### ISSUE TITLE
Models not loading

### ISSUE THREAD

**Issue by BradleyWiebe** [Webura/mongooseadmin#1]
I'm getting the following error:
"NetworkError: 500 Internal Server Error - http://127.0.0.1:5000/admin/models"

In app.js:

```
var mongooseadmin = require('mongooseadmin');
var options = {
    title: 'The Hub'
    };
app.use(mongooseadmin('/admin', options));
```

In .models/user.js:

```
//new user model

var mongoose = require('mongoose');
var multer  = require('multer');
var bcrypt = require('bcrypt-nodejs');
var crypto = require('crypto');
var secrets = require('../config/secrets');
var timestamps = require('mongoose-timestamp');
var Schema = mongoose.Schema;
var ObjectId = Schema.ObjectId;
var userSchema = new mongoose.Schema({
email: { type: String, unique: true, lowercase: true },
password: String,
profile: {
  name: { type: String, default: '' },
  gender: { type: String, default: '' },
  location: { type: String, default: '' },
  website: { type: String, default: '' },
  picture: { type: String, default: '' }
},
  post             : [postSchema],
  resetPasswordToken: String,
  resetPasswordExpires: Date
});

module.exports = mongoose.model('User', userSchema);
```

The admin page loads at /admin but appears blank except for the title. Any idea why?

**Comment by Webura** [comment]
Hi Bradley!

Thank you for the issue ticket I have just updated mongooseadmin so that it supports sub documents, can you check again. Unfortunately we don't support arrays yet. 

But if you would like to contribute, I would be very happy.

**Comment by BradleyWiebe** [comment]
Hey Johnny,

Great thanks, its working now... but, I had to remove the array from the user model.

By the way, great work on this so far. I looked at Keystone, but had two drawbacks: having to change the models to fit Keystone's lists, and the fact that it's intended to be a CMS. Your lightweight approach is awesome.

Sure, I'd be interested to help build sub-doc array support. 

-Brad
